"""Builds a small Phone Link style notifications database in WAL mode with
made-up notifications, and a phoneapps database with made-up icons, and
writes them as base64 into fixture.ts.

The WAL is copied while the connection is still open, because closing the
last connection checkpoints it into the main file and deletes it.
"""
import base64, json, os, random, shutil, sqlite3, struct, tempfile, zlib

SCHEMA = '''CREATE TABLE "notifications"(
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "notification_id" TEXT NOT NULL UNIQUE,
    "package_name" TEXT NOT NULL,
    "json" TEXT NOT NULL,
    "post_time" INTEGER NOT NULL,
    "state" INTEGER NOT NULL DEFAULT 0,
    "anonymous_id" TEXT
)'''

def note(key, pkg, app, title, text, post, **extra):
    d = {"id": 1, "key": key, "groupKey": key, "packageName": pkg, "appName": app,
         "isGroup": True, "isOngoing": False, "flags": 17, "postTime": post, "timestamp": post - 2,
         "title": title, "text": text, "bigText": text, "subText": ""}
    d.update(extra)
    return json.dumps(d, ensure_ascii=False, separators=(',', ':'))

here = os.path.dirname(os.path.abspath(__file__))
tmp = tempfile.mkdtemp()
db = os.path.join(tmp, 'n.db')
c = sqlite3.connect(db)
c.execute('PRAGMA page_size=4096')
c.execute('PRAGMA journal_mode=WAL')
c.execute('PRAGMA wal_autocheckpoint=0')
c.execute(SCHEMA)
c.execute('CREATE INDEX "notifications_post_time_idx" ON "notifications"("post_time" DESC)')
c.commit()
c.execute('PRAGMA wal_checkpoint(TRUNCATE)')  # schema goes to the main file, rows stay in the WAL

rows = [
    ('k-mail', 'com.example.mail', 'Mail', 'Ada Lovelace', 'テスト通知', 1791273227000,
     {"bigText": 'テスト通知\n本文の1行目\n\n本文の2行目\n本文の3行目\n本文の4行目'}),
    ('k-food', 'com.example.food', 'FoodNow', 'Order received', 'The shop is preparing your order', 1791273300000, {}),
    ('k-summary', 'com.example.mail', 'Mail', '', '2 new messages', 1791273310000, {"flags": 17 | 0x200}),
    ('k-gone', 'com.example.chat', 'Chat', 'Bob', 'This one gets dismissed', 1791273320000, {}),
    ('k-long', 'com.example.news', 'News', 'Long read', 'x' * 9000, 1791273330000, {}),
    # A music player's playback controls: ongoing, not clearable, category transport.
    ('k-music', 'com.example.player', 'Player', 'A song', 'An artist', 1791273340000,
     {"isOngoing": True, "isClearable": False, "category": "transport", "flags": 0x62}),
]
for key, pkg, app, title, text, post, extra in rows:
    c.execute('INSERT INTO notifications(notification_id, package_name, json, post_time) VALUES (?,?,?,?)',
              (key, pkg, note(key, pkg, app, title, text, post, **extra), post))
c.commit()
before = os.path.getsize(db + '-wal')  # the WAL only grows, so this prefix is the earlier state
c.execute("DELETE FROM notifications WHERE notification_id='k-gone'")
c.execute("UPDATE notifications SET json=? WHERE notification_id='k-food'",
          (note('k-food', 'com.example.food', 'FoodNow', 'On the way', 'Arriving in 12 min', 1791273400000),))
c.commit()

main = open(db, 'rb').read()
wal = open(db + '-wal', 'rb').read()
c.close()

# Phone Link keeps each phone app's icon as a PNG in phoneapps.db. Made-up
# icons for Mail and FoodNow; News has none. FoodNow's is noise, so it does
# not compress and spills into overflow pages, as real icons do.
APPS_SCHEMA = '''CREATE TABLE "phone_apps"(
    "app_id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "app_name" TEXT NOT NULL,
    "package_name" TEXT NOT NULL UNIQUE,
    "version" TEXT NOT NULL,
    "etag" INTEGER NOT NULL DEFAULT 0,
    "favorite_rank" INTEGER NOT NULL DEFAULT -1,
    "blob" BLOB,
    "last_updated_time" INTEGER NOT NULL DEFAULT 0,
    "checksum" INTEGER NOT NULL DEFAULT 0,
    "phoneapp_web_url" TEXT)'''

def png(size, pixel):
    def chunk(kind, data):
        return struct.pack('>I', len(data)) + kind + data + struct.pack('>I', zlib.crc32(kind + data))
    rows = b''.join(b'\x00' + b''.join(pixel(x, y) for x in range(size)) for y in range(size))
    return (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', size, size, 8, 2, 0, 0, 0))
            + chunk(b'IDAT', zlib.compress(rows)) + chunk(b'IEND', b''))

rng = random.Random(7)
apps_db = os.path.join(tmp, 'apps.db')
a = sqlite3.connect(apps_db)
a.execute('PRAGMA page_size=4096')
a.execute(APPS_SCHEMA)
for name, pkg, icon in [
    ('Mail', 'com.example.mail', png(2, lambda x, y: b'\xd0\x40\x30')),
    ('FoodNow', 'com.example.food', png(48, lambda x, y: bytes(rng.randrange(256) for _ in range(3)))),
    ('News', 'com.example.news', None),
]:
    a.execute('INSERT INTO phone_apps(app_name, package_name, version, blob) VALUES (?,?,?,?)',
              (name, pkg, '1.0', icon))
a.commit()
a.close()
apps = open(apps_db, 'rb').read()
shutil.rmtree(tmp)

with open(os.path.join(here, 'fixture.ts'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by make_fixture.py: made-up notifications only.\n')
    f.write(f"export const MAIN_B64 = '{base64.b64encode(main).decode()}'\n")
    f.write(f"export const WAL_B64 = '{base64.b64encode(wal).decode()}'\n")
    f.write("// The WAL before the delete and the update: the food order still says 'Order received'.\n")
    f.write(f"export const WAL_BEFORE_LENGTH = {before}\n")
    f.write("// phoneapps.db: icons for Mail and FoodNow, none for News.\n")
    f.write(f"export const APPS_B64 = '{base64.b64encode(apps).decode()}'\n")
print('main', len(main), 'wal', len(wal), 'apps', len(apps))
